// Copyright Epic Games, Inc. All Rights Reserved.

#include "GAS/ERGameplayTags.h"

namespace ERTags
{
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Stun,        "State.CC.Stun");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Airborne,    "State.CC.Airborne");
	UE_DEFINE_GAMEPLAY_TAG(State_Frustrated,     "State.Frustrated");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Snare,       "State.CC.Snare");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Silence,     "State.CC.Silence");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Disarm,      "State.CC.Disarm");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Slow,        "State.CC.Slow");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_Blind,       "State.CC.Blind");
	UE_DEFINE_GAMEPLAY_TAG(State_CC_VisionBlock, "State.CC.VisionBlock");

	UE_DEFINE_GAMEPLAY_TAG(State_Stealth,        "State.Stealth");
	UE_DEFINE_GAMEPLAY_TAG(State_Invulnerable,   "State.Invulnerable");
	UE_DEFINE_GAMEPLAY_TAG(State_DamageImmune,   "State.DamageImmune");
	UE_DEFINE_GAMEPLAY_TAG(State_Unstoppable,    "State.Unstoppable");
	UE_DEFINE_GAMEPLAY_TAG(State_Untargetable,   "State.Untargetable");
	UE_DEFINE_GAMEPLAY_TAG(State_CCImmune,       "State.CCImmune");
	UE_DEFINE_GAMEPLAY_TAG(State_Bleeding,       "State.Bleeding");
	UE_DEFINE_GAMEPLAY_TAG(State_Adrenaline,     "State.Adrenaline");
	UE_DEFINE_GAMEPLAY_TAG(State_Riding,         "State.Riding");
	UE_DEFINE_GAMEPLAY_TAG(State_AnimHold,       "State.AnimHold");
	UE_DEFINE_GAMEPLAY_TAG(State_Gathering,      "State.Gathering");

	UE_DEFINE_GAMEPLAY_TAG(State_Block_Movement,    "State.Block.Movement");
	UE_DEFINE_GAMEPLAY_TAG(State_Block_BasicAttack, "State.Block.BasicAttack");
	UE_DEFINE_GAMEPLAY_TAG(State_Block_Skill,       "State.Block.Skill");

	UE_DEFINE_GAMEPLAY_TAG(Ability_Form_Channeled,      "Ability.Form.Channeled");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Form_NextAttackBuff, "Ability.Form.NextAttackBuff");

	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot,   "Ability.Slot");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_P, "Ability.Slot.P");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_Q, "Ability.Slot.Q");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_W, "Ability.Slot.W");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_E, "Ability.Slot.E");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_R, "Ability.Slot.R");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_D, "Ability.Slot.D");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_Attack, "Ability.Slot.Attack");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_Q_Recast, "Ability.Slot.Q.Recast");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_W_Recast, "Ability.Slot.W.Recast");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_E_Recast, "Ability.Slot.E.Recast");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_R_Recast, "Ability.Slot.R.Recast");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_D_Recast, "Ability.Slot.D.Recast");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_Q_Execute, "Ability.Slot.Q.Execute");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_W_Execute, "Ability.Slot.W.Execute");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_E_Execute, "Ability.Slot.E.Execute");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_R_Execute, "Ability.Slot.R.Execute");
	UE_DEFINE_GAMEPLAY_TAG(Ability_Slot_D_Execute, "Ability.Slot.D.Execute");

	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_P, "Cooldown.Slot.P");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_Q, "Cooldown.Slot.Q");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_W, "Cooldown.Slot.W");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_E, "Cooldown.Slot.E");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_R, "Cooldown.Slot.R");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_D, "Cooldown.Slot.D");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Slot_Attack, "Cooldown.Slot.Attack");

	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Hammer,      "Cooldown.Weapon.Hammer");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Bat,         "Cooldown.Weapon.Bat");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Axe,         "Cooldown.Weapon.Axe");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Dagger,      "Cooldown.Weapon.Dagger");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Shuriken,    "Cooldown.Weapon.Shuriken");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_SniperRifle, "Cooldown.Weapon.SniperRifle");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Pistol,      "Cooldown.Weapon.Pistol");
	UE_DEFINE_GAMEPLAY_TAG(Cooldown_Weapon_Throw,       "Cooldown.Weapon.Throw");


	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_P, "Recast.Slot.P");
	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_Q, "Recast.Slot.Q");
	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_W, "Recast.Slot.W");
	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_E, "Recast.Slot.E");
	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_R, "Recast.Slot.R");
	UE_DEFINE_GAMEPLAY_TAG(Recast_Slot_D, "Recast.Slot.D");

	UE_DEFINE_GAMEPLAY_TAG(Damage_Type_BasicAttack, "Damage.Type.BasicAttack");
	UE_DEFINE_GAMEPLAY_TAG(Damage_Type_Skill,       "Damage.Type.Skill");
	UE_DEFINE_GAMEPLAY_TAG(Damage_Type_True,        "Damage.Type.True");
	UE_DEFINE_GAMEPLAY_TAG(Damage_Secondary,        "Damage.Secondary");

	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_CCDuration,           "SetByCaller.CCDuration");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Cooldown,             "SetByCaller.Cooldown");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Cost,                 "SetByCaller.Cost");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_PhaseDuration,        "SetByCaller.PhaseDuration");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_StateDuration,        "SetByCaller.StateDuration");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_LostHP_RegenMin,      "SetByCaller.LostHP.RegenMin");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_LostHP_RegenMax,      "SetByCaller.LostHP.RegenMax");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_LostHP_SkillAmpMin,   "SetByCaller.LostHP.SkillAmpMin");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_LostHP_SkillAmpMax,   "SetByCaller.LostHP.SkillAmpMax");

	UE_DEFINE_GAMEPLAY_TAG(State_Casting,    "State.Casting");
	UE_DEFINE_GAMEPLAY_TAG(State_Recovering, "State.Recovering");
	UE_DEFINE_GAMEPLAY_TAG(State_Unarmed,    "State.Unarmed");
	UE_DEFINE_GAMEPLAY_TAG(State_InCombat,   "State.InCombat");
	UE_DEFINE_GAMEPLAY_TAG(State_ConsumeOnAttack, "State.ConsumeOnAttack");
	UE_DEFINE_GAMEPLAY_TAG(State_NextAttackBuff, "State.NextAttackBuff");
	UE_DEFINE_GAMEPLAY_TAG(State_Shielded,     "State.Shielded");
	UE_DEFINE_GAMEPLAY_TAG(State_WilsonAway,   "State.Wilson.Away");
	UE_DEFINE_GAMEPLAY_TAG(State_LostHPStats,  "State.Passive.LostHPStats");
	UE_DEFINE_GAMEPLAY_TAG(State_Bubble,       "State.Sissela.Bubble");
	UE_DEFINE_GAMEPLAY_TAG(Event_Wilson_Joined, "Event.Wilson.Joined");
	UE_DEFINE_GAMEPLAY_TAG(Event_Input_Move, "Event.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(Event_Skill_Aim,  "Event.Skill.Aim");
	UE_DEFINE_GAMEPLAY_TAG(Event_Kill_Dealt, "Event.Kill.Dealt");
	UE_DEFINE_GAMEPLAY_TAG(Event_Hit_Dealt,  "Event.Hit.Dealt");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SlowPercent,          "SetByCaller.SlowPercent");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_OnHitMagnitude,       "SetByCaller.OnHitMagnitude");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Charges,              "SetByCaller.Charges");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SlowMultiplier,       "SetByCaller.SlowMultiplier");

	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_MaxHP,                "SetByCaller.MaxHP");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_MaxVP,                "SetByCaller.MaxVP");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_HP,                   "SetByCaller.HP");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_VP,                   "SetByCaller.VP");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_HPRegen,              "SetByCaller.HPRegen");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_VPRegen,              "SetByCaller.VPRegen");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_AttackPower,          "SetByCaller.AttackPower");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Defense,              "SetByCaller.Defense");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_AttackSpeed,          "SetByCaller.AttackSpeed");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_MoveSpeed,            "SetByCaller.MoveSpeed");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Sight,                "SetByCaller.Sight");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_AttackRange,          "SetByCaller.AttackRange");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_CritChance,           "SetByCaller.CritChance");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_CritDamageUp,         "SetByCaller.CritDamageUp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SkillAmp,             "SetByCaller.SkillAmp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_BasicAtkAmp,          "SetByCaller.BasicAtkAmp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_DefPenPercent,        "SetByCaller.DefPenPercent");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_DefPenFlat,           "SetByCaller.DefPenFlat");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_DamageUp,             "SetByCaller.DamageUp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_FinalDamageUpPercent, "SetByCaller.FinalDamageUpPercent");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_FinalDamageUpFlat,    "SetByCaller.FinalDamageUpFlat");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SkillHaste,           "SetByCaller.SkillHaste");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_DamageDown,           "SetByCaller.DamageDown");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_BasicAtkDamageDown,   "SetByCaller.BasicAtkDamageDown");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SkillDamageDown,      "SetByCaller.SkillDamageDown");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_SlowResist,           "SetByCaller.SlowResist");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_CCResist,             "SetByCaller.CCResist");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_Lifesteal,            "SetByCaller.Lifesteal");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_OmniLifesteal,        "SetByCaller.OmniLifesteal");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_HealAmp,              "SetByCaller.HealAmp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_OutOfCombatRegen,     "SetByCaller.OutOfCombatRegen");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_ModeDamageUp,         "SetByCaller.ModeDamageUp");
	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_ModeDamageDown,       "SetByCaller.ModeDamageDown");

	UE_DEFINE_GAMEPLAY_TAG(SetByCaller_HealAmount,           "SetByCaller.HealAmount");

	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_Base,             "Data.Damage.Base");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_APRatio,          "Data.Damage.APRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_BonusAPRatio,     "Data.Damage.BonusAPRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_SkillAmpRatio,    "Data.Damage.SkillAmpRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_MaxHPRatio,       "Data.Damage.MaxHPRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_CurHPRatio,       "Data.Damage.CurHPRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_LostHPRatio,      "Data.Damage.LostHPRatio");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_HPFloor, "Data.Damage.HPFloor");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_Multiplier, "Data.Damage.Multiplier");
	UE_DEFINE_GAMEPLAY_TAG(Data_Damage_TargetLostHPScaleMax, "Data.Damage.TargetLostHPScaleMax");

	UE_DEFINE_GAMEPLAY_TAG(Damage_Shape_AoE,    "Damage.Shape.AoE");
	UE_DEFINE_GAMEPLAY_TAG(Actor_Type_Wildlife, "Actor.Type.Wildlife");
	UE_DEFINE_GAMEPLAY_TAG(Actor_Type_Boss,     "Actor.Type.Boss");

	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_Dance, "Pres.Anim.Dance");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_Death, "Pres.Anim.Death");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_Gather, "Pres.Anim.Gather");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Prop_Bike,   "Pres.Prop.Bike");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Attack, "Pres.Sfx.Attack");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Hit, "Pres.Sfx.Hit");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast, "Pres.Sfx.SkillCast");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit, "Pres.Sfx.SkillHit");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Die, "Pres.Sfx.Die");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_Appear, "Pres.Anim.Appear");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_EndBattle, "Pres.Anim.EndBattle");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Appear, "Pres.Sfx.Appear");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Discover, "Pres.Sfx.Discover");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_BewareStart, "Pres.Anim.BewareStart");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_BewareLoop, "Pres.Anim.BewareLoop");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_BewareEnd, "Pres.Anim.BewareEnd");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_SleepStart, "Pres.Anim.SleepStart");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_SleepLoop, "Pres.Anim.SleepLoop");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_Wake, "Pres.Anim.Wake");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Beware, "Pres.Sfx.Beware");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast_Q, "Pres.Sfx.SkillCast.Q");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast_W, "Pres.Sfx.SkillCast.W");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast_E, "Pres.Sfx.SkillCast.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast_R, "Pres.Sfx.SkillCast.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCast_D, "Pres.Sfx.SkillCast.D");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_Q, "Pres.Sfx.SkillHit.Q");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_W, "Pres.Sfx.SkillHit.W");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_E, "Pres.Sfx.SkillHit.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_R, "Pres.Sfx.SkillHit.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_D, "Pres.Sfx.SkillHit.D");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_AttackEnhanced, "Pres.Sfx.AttackEnhanced");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_HitEnhanced, "Pres.Sfx.HitEnhanced");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_EnhanceReady, "Pres.Sfx.EnhanceReady");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillAim_R, "Pres.Sfx.SkillAim.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHit_P, "Pres.Sfx.SkillHit.P");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLoop_P, "Pres.Sfx.SkillLoop.P");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLoopStart_P, "Pres.Sfx.SkillLoopStart.P");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLand_E, "Pres.Sfx.SkillLand.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillHitLate_Q, "Pres.Sfx.SkillHitLate.Q");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLoop_W, "Pres.Sfx.SkillLoop.W");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLoop_R, "Pres.Sfx.SkillLoop.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLoopStart_R, "Pres.Sfx.SkillLoopStart.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillRecast_R, "Pres.Sfx.SkillRecast.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_Join, "Pres.Sfx.Join");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillMove_Q, "Pres.Sfx.SkillMove.Q");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLand_Q, "Pres.Sfx.SkillLand.Q");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillBurst_W, "Pres.Sfx.SkillBurst.W");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillStun_E, "Pres.Sfx.SkillStun.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillPull_E, "Pres.Sfx.SkillPull.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillShield_E, "Pres.Sfx.SkillShield.E");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillCount_R, "Pres.Sfx.SkillCount.R");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Sfx_SkillLand_R, "Pres.Sfx.SkillLand.R");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Attack, "GameplayCue.Pres.Attack");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Hit, "GameplayCue.Pres.Hit");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Aim, "GameplayCue.Pres.Aim");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Land, "GameplayCue.Pres.Land");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Ready, "GameplayCue.Pres.Ready");
	UE_DEFINE_GAMEPLAY_TAG(GameplayCue_Pres_Sfx, "GameplayCue.Pres.Sfx");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_AttackEnhanced, "Pres.Anim.AttackEnhanced");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_ModeStart, "Pres.Anim.ModeStart");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_ModeIdle, "Pres.Anim.ModeIdle");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_ModeRun, "Pres.Anim.ModeRun");
	UE_DEFINE_GAMEPLAY_TAG(Pres_Anim_ModeEnd, "Pres.Anim.ModeEnd");
	UE_DEFINE_GAMEPLAY_TAG(Mode, "Mode");
	UE_DEFINE_GAMEPLAY_TAG(Mode_Sniper, "Mode.Sniper");
	UE_DEFINE_GAMEPLAY_TAG(Mode_Bubble, "Mode.Bubble");
	UE_DEFINE_GAMEPLAY_TAG(Mode_Chainsaw, "Mode.Chainsaw");
}
